@accentColor = @sky
defaultFont  = 15 "Tektur", "Noto Sans", Roboto, Arial

# --- Configurações Gerais de Componentes ---
Component.foreground  = @text
Component.focusColor  = @accentColor
Component.accentColor = @accentColor
Component.arc         = 12

# --- Painéis e Janelas ---
Panel.background    = @base
Frame.background    = @base
RootPane.background = @base
Label.foreground    = @text

# --- Barra de Título (Title Pane) ---
TitlePane.background            = @crust
TitlePane.borderColor           = @base
TitlePane.buttonHoverBackground = @surface1
TitlePane.closeHoverBackground  = @red
TitlePane.closeHoverForeground  = @base

# --- Botões ---
Button.arc = 12
Button.background         = @base
Button.foreground         = @text
Button.focusedBackground  = @surface0
Button.hoverBackground    = mix(@surface1, @accentColor, 80%)
Button.borderColor        = @surface0
Button.hoverBorderColor   = @accentColor
Button.focusedBorderColor = @accentColor
Button.pressedBackground  = @accentColor
Button.pressedForeground  = @base
Button.borderWidth        = 2

# --- Campos de Texto ---
TextComponent.arc             = 12
TextField.background          = @surface0
TextField.foreground          = @text
TextField.selectionBackground = @accentColor
TextField.selectionForeground = @crust

# --- ScrollBar ---
ScrollBar.thumbColor = @surface2
ScrollBar.trackColor = @mantle

# --- JOptionPane ---
OptionPane.background             = @base
OptionPane.messageForeground      = @text
OptionPane.messageArea.background = @base
OptionPane.buttonArea.background  = @base

[style].NavContainer=\
background: @mantle;\

######################################################## MouseEventsPage

@labelTitleBackground = @surface0
@labelTitleFontSize   = 40 bold

@labelExampleBackground = mix(@overlay0, @base, 50%)
@labelExampleBorder     = 0, 0, 0, 0, @overlay0, 3
@labelExampleRadius     = 48
@labelExampleFont       = 16

[light]@labelExampleOpacity = 30%
[dark]@labelExampleOpacity  = 60%
@backgroundEnter      = mix(@green,  @base, @labelExampleOpacity)
@backgroundExited     = mix(@red,    @base, @labelExampleOpacity)
@backgroundPressed    = mix(@yellow, @base, @labelExampleOpacity)
@backgroundReleased   = mix(@peach,  @base, @labelExampleOpacity)
@backgroundMoved      = mix(@sky,    @base, @labelExampleOpacity)
@backgroundDragged    = mix(@teal,   @base, @labelExampleOpacity)
@backgroundWheelMoved = mix(@mauve,  @base, @labelExampleOpacity)

@borderEnter      = 0, 0, 0, 0, @green,  3
@borderExited     = 0, 0, 0, 0, @red,    3
@borderPressed    = 0, 0, 0, 0, @yellow, 3
@borderReleased   = 0, 0, 0, 0, @peach,  3
@borderMoved      = 0, 0, 0, 0, @sky,    3
@borderDragged    = 0, 0, 0, 0, @teal,   3
@borderWheelMoved = 0, 0, 0, 0, @mauve,  3

# ---------------------------

[style].labelTitle=\
background: @labelTitleBackground;\
foreground: @text;\
font:       @labelTitleFontSize;\

[style].labelExample=\
background: @labelExampleBackground;\
border:     @labelExampleBorder;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mouseEnter=\
background: @backgroundEnter;\
border:     @borderEnter;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mouseExit=\
background: @backgroundExited;\
border:     @borderExited;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mousePressed=\
background: @backgroundPressed;\
border:     @borderPressed;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mouseReleased=\
background: @backgroundReleased;\
border:     @borderReleased;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mouseMoved=\
background: @backgroundMoved;\
border:     @borderMoved;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mouseDragged=\
background: @backgroundDragged;\
border:     @borderDragged;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\

[style].mouseWheelMoved=\
background: @backgroundWheelMoved;\
border:     @borderWheelMoved;\
arc:        @labelExampleRadius;\
font:       @labelExampleFont;\


######################################################## KeyboardEventsPage

@labelKeyBackground = mix(@overlay0, @base, 50%)
@labelKeyForeground = @accentColor
@labelKeyFont       = 40

# ---------------------------

[style].labelKey=\
background: @labelKeyBackground;\
foreground: @labelKeyForeground;\
font:       @labelKeyFont;\
